import turtle
t=turtle.Turtle()
color = input("Nhap mau hoac ma mau: ")
d=float(input("Nhap chieu dai hinh chu nhat: "))
r=float(input("Nhap chieu rong hinh chu nhat: "))
t.hideturtle()
t.color(color)
t.begin_fill()
t.forward(d)
t.left(90)
t.forward(r)
t.left(90)
t.forward(d)
t.left(90)
t.forward(r)
t.left(90)
t.end_fill()