import turtle
t=turtle.Turtle()
t.pensize(3)
t.pencolor("Green")
t.fillcolor("Blue")
a=int(input("Nhap chieu dai canh a: "))
b=int(input("Nhap chieu dai canh b: "))
t.forward(a)
t.left(90)
t.forward(b)
t.left(90)
t.forward(a)
t.left(90)
t.forward(b)